import packageJson from '../package.json';
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Grid from './grid'
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [sessionId, setSessionId] = useState('');

  useEffect(() => {
    if (sessionId === '') {
      setSessionId(Math.random().toString(36).substring(2, 10));
    }
  }, []);

  return (
    <>
      <Head>
        <title>{packageJson.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid sessionId={sessionId} />
    </>
  )
}
