name: Python Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set file permissions
        run: chmod +x tests/setup_test_env.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scipy adjustText flask flask-cors requests
          mkdir data
          mkdir data/ml-10M100K
          python tests/setup_test_env.py
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo $PYTHONPATH
          python -m unittest discover tests
